[package]
name = "db-midpj"
version = "0.1.0"
edition = "2021"

[workspace]
members = [".", "entity"]

[workspace.dependencies]
# 跨 Package 的依赖。各个 Package 只需要在 Cargo.toml 中声明依赖 { workspace = true } 即可。
sea-orm = { version = "^0.11", features = ["sqlx-mysql", "runtime-actix-native-tls", "macros"] }
serde = { version = "^1.0", features = ["derive"] }

[dependencies]
axum = "^0.6"
tokio = { version = "^1.28", features = ["macros", "rt-multi-thread"] }
tower = "^0.4"
sea-orm = { workspace = true }