[package]
name = "entity"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
fromsuper = "^0.1"
sea-orm = { workspace = true }
serde = { workspace = true }
utoipa = { workspace = true }